# General Settings
title = "Pensieri in codice"
baseURL = "https://pensieriincodice.it/" #YOUR SITE URL
languageCode = "it-IT"
theme = "ryancv"
resourceDir = "resources"
paginate = 4
summaryLength = 20
DefaultContentLanguage = "it"

[markup.goldmark.renderer]
unsafe= true

# Menu Settings
##
### to add or remove card (or menu item)
### param "name" - Menu item name
### param "pre" - Menu item icon class, all icons class you can see here https://ionicons.com/v4/
### param "identifier" - Menu item url slug
### param "url" - Menu item url
### param "sections" - list of sections what will be show of each card, all prebuild sections name see in documentations
[menu]
[[menu.main]]
  identifier = "about"
  name = "Home"
  pre = "mic"
  url = "#about-card"
  weight = 1
  [menu.main.params]
    builder = [
      "motto",
      "platforms",
      "facts",
      "partners",
      "netzero"
#      "about",
#      "services",
#      "pricing",
#      "testimonials"
    ]
[[menu.main]]
  identifier = "history"
  name = "Storia"
  pre = "book"
  url = "#history-card"
  weight = 4
  [menu.main.params]
    builder = [
      "history",
     # "skills"
    ]
[[menu.main]]
  identifier = "blog"
  name = "Ultime novità"
  pre = "alert-circle"
  url = "#blog-card"
  weight = 2
  [menu.main.params]
    builder = [
      "blog"
    ]
[[menu.main]]
  identifier = "support"
  name = "Sostieni"
  pre = "gift"
  url = "#support-card"
  weight = 3
  [menu.main.params]
    builder = [
      "support",
      "rewards",
      "supporters",
      #"contact-info",
      #"contact-form"
    ]
[[menu.main]]
  identifier = ""
  name = "Archivio episodi"
  pre = "play"
  url = "episodes"
  weight = 5
  [menu.main.params]
    builder = [
  #"supporters"
  #"contact-info",
  #"contact-form"
    ]

[[menu.sidebar]]
  identifier = "blog"
  name = "News"
  url = "blog"
  weight = 1
[[menu.sidebar]]
  identifier = "episodes"
  name = "Archivio episodi"
  url = "episodes"
  weight = 2

# Main Settings
[params]
skinColor = "orange-pic" #TEMPLATE SKIN COLOR: [ blue, green, orange, pink, purple, red ]. If empty colors taken from thenes/ryan/assets/scss/_settings.scss
skinDark = 0 #TEMPLATE UI: [ 1 - yes, 0 - no ]
rtl = 0 #TEMPLATE RTL MODE: [ 1 - yes, 0 - no ]
skinMinimal = 0 #TEMPLATE MINIMAL SKIN: [ 1 - yes, 0 - no ]
dateFormat = "January 2, 2006"
authorName = "Daniele Galano Web & Graphic Designer"
disqusComments = "your_disqus_shortname" #YOUR DISQUS COMMENTS SHORTNAME
formspreeURL = "https://formspree.io/f/your_api_key" #YOUR FORMSPREE URL
googleAnalytics = "" #YOUR GOOGLE ANALYTICS CODE

# Background
[params.background]
type = "default" #BACKGROUND TYPE: [ default, blured ]

# Google MAPS
[params.googleMaps]
key = "" #YOUR GOOGLE MAPS API KEY: leave empty if you want to hide Google Maps
lat = "40.773328" #YOUR GOOGLE MAPS LATITUDE
long = "-73.960088" #YOUR GOOGLE MAPS LONGITUDE
zoom = "14" #YOUR GOOGLE MAPS ZOOM VALUE

# Sidebar
[params.sidebar]
enable = 1 #SIDEBAR SHOW: [ 1 - yes, 0 - no ]
search = 0 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
categories = 1 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
tags = 1 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
menuWidget = 1 #SIDEBAR MENU WIDGET: [ 1 - yes, 0 - no ]

# Animation Settings
[params.animation]
in = "fadeInLeft" #ANIMATION IN: [ rotateInUpLeft, rollIn, jackInTheBox, fadeIn, fadeInUp, fadeInLeft ]
out = "fadeOutLeft" #ANIMATION OUT: [ rotateOutUpLeft, rollOut, jackOutTheBox, fadeOut, fadeOutUp, fadeOutLeft ]

# Portfolio Settings
[params.portfolio]
homeNumOfItems = 12
[[params.portfolio.filters]]
name = "Photo"
slug = "photo"
[[params.portfolio.filters]]
name = "Video"
slug = "video"
[[params.portfolio.filters]]
name = "Music"
slug = "music"
[[params.portfolio.filters]]
name = "Design"
slug = "design"

[params.podcast]
title = "Hugo Podcast"
subtitle = "Subtitle"
summary = "Summary"
authors = [ "Author" ]
email = "example@example.com"
image = "/img/podcast-logo.png"
audio_base_url = "https://cdn.example.com/podcast/"
copyright = "Copyright"
category = "Category"
sub_category = "Sub Category"
explicit = "no"
itunesID = 12345677
itunes_type = "episodic"  # accepted values are: "episodic" or "serial"
updatePeriod = "weekly"
updateFrequency = 1
funding_url = "https://pensieriincodice.it/#support-card"
funding_text = "Sostieni il podcast"

# Sitemap Settings
[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[outputFormats.podcast]
MediaType = "application/rss+xml"
BaseName = "index"
path = "/feed/"
IsHTML = false
IsPlainText = true
noUgly = true
Rel = "alternate"

[outputs]
home = ["HTML", "RSS", "JSON", "podcast"]